id: PACAC7D73
initial_creation_type: ocr
source_metadata:
  volumes:
    bcd11d2535df4f74b78dece3ee7a90fb:
      base_file: v012.txt
      image_group_id: I1PD95857
      title: རྡོ་རྗེ་རྣལ་འབྱོར་མ་ལ་བསྟོད་པ།
      total_pages: 1544
      volume_number: 12
